### PR TITLE
Enable optional evaluation of docstrings and annotations

### PR DESCRIPTION
**Pull request by AaronCritchley**

### CODE REVIEW

**Comment by AaronCritchley** [comment]
FYI, I have turned off the `assert` check in codacy, as it was complaining about every time we used assert (in tests) and putting it as a negative on the code quality metrics.

Published to PyPI under 2019.1b3, I think this should be a candidate for 2019.1 providing no issues in testing 😄

**Comment by AaronCritchley** [comment]
Published to PyPI under 2019.1b4 with additional fix for ContractsMeta - likely need to discuss ContractsMeta issues before releasing 2019.1 as the area does not not have sufficient unit tests inside the main codebase to catch the edge cases we've hit in our internal code.

**Comment by dwillmer** [comment]
LGTM... did you want this merged, or are you still working on it?

**Comment by AaronCritchley** [comment]
This can be merged, some further (separate) work before 2019.1 is required
though

**Pull request merged**
